config/routes.rb
Rails.application.routes.draw do
  resources :repair

  root 'welcome#index'

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/code_controller.rb
class RepairController < ApplicationController
  def index
    @repair = Repair.all
  end
  def show
    @repair = Repair.find(params[:id])
  end

  def new
    @repair = Repair.new
  end


    def create
  @repair = Repair.new(repair_params)

 if @repair.save
  redirect_to @repair
else
  render 'new'
  end


def update
  @repair = Repair.find(params[:id])

  if @repair.update(repair_params)
    redirect_to @repair
  else
    render 'edit'
  end



private
  def repair_params
    params.require(:repair).permit(:title, :text)
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repair_helper.rb
module RepairHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClimberRps0</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/repair/edit.html.erb
<h1>Editing Repair</h1>

<%= form_for :repair, url: repair_path(@repair), method: :patch do |f| %>

  <% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@repair.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @repair.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', repair_path %>

app/views/repair/index.hmtl.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'repairs' %>
<%= link_to 'New Repair', new_repair_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <% @repairs.each do |repair| %>
    <tr>
      <td><%= repair.title %></td>
      <td><%= repair.text %></td>
      <td><%= link_to 'Show', repair_path(repair) %></td>
      <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
    </tr>
  <% end %>
</table>

app/views/repair/new.html.erb
<h1>New Repair Request</h1>

<%= form_for :repair, url: repair_path do |f| %>
<% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@repair.errors.count, "error") %> prohibited
        this repair from being saved:
      </h2>
      <ul>
        <% @repair.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', repairs_path %>

app/views/repair/show.hmtl.erb
<p>
  <strong>Title:</strong>
  <%= @repair.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @repair.text %>
</p>


<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>